### PR TITLE
DO NOT MERGE: emacs: fix differing filename/feature names

### PR DESCRIPTION
**Pull request by thomasf**
also moves the emacs lisp code into lisp/ so that adding that path into the
load-path doesn't bring in files which Emacs doesn't load.

### CODE REVIEW

**Comment by thomasf** [comment]
To keep the readme simple I did not change it to a "two liner" even though require is a slightly better method for only loading the feature once. 

The resulting error from specifying the wrong path using `(load)` is probably a small bit easier to understans than `(require)` for people who doesn't know what the `load-path` is.

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Thanks!

**Comment by thomasf** [comment]
But theres an error.. I'm fixing it now

**Comment by stapelberg** [comment]
Ah, I saw that too late.

**Comment by thomasf** [comment]
it's non obvious how to get the relative lisp/go-errchech.el path correctly.. I made an error first by just testing it from the expanderr directory.. I'll have a patch soon

**Pull request merged**
