### PR TITLE
Implement -format=json (for vim-go)

### PR DESCRIPTION
**Pull request by stapelberg**
related to #1

### CODE REVIEW

**Comment by stapelberg** [comment]
@fatih Could you take a quick look at this and let me know if the interface is what vim-go will be able to use? I modeled it after gomodifytags, but perhaps I missed something…

**Comment by arp242** [comment]
I added the a basic integration in Vim-go (see above reference), and this PR seems to work well :+1:

**Comment by arp242** [comment]
Is there any further work that needs to be done before this can be merged @stapelberg? Anything I can do to help?

**Comment by stapelberg** [comment]
I was hoping for @fatih to weigh in, but if you say this works fine, then let’s go ahead and merge it as-is. We can always fix it later.

**Comment by arp242** [comment]
Thanks! I'll continue with the vim-go integration and look at improving some of the other issues I reported a while ago next week, as I'll be away most of this week.

**Pull request merged**
